apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: streamer
  name: streamer-ginflix
  namespace: ginflix
spec:
  replicas: 1
  selector:
    matchLabels:
      run: streamer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: streamer
    spec:
      containers:
        - image: nginx:latest
          name: streamer
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: streamer-cm0
              subPath: default.conf
            - mountPath: /var/www/html
              name: videos
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: nginx.conf
                path: default.conf
            name: streamer-cm0
          name: streamer-cm0
        - name: videos
          persistentVolumeClaim:
            claimName: streamer-videos-ginflix
