apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    run: streamer-videos
  name: streamer-videos-ginflix
  namespace: ginflix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
