apiVersion: v1
kind: Service
metadata:  
  name: web
  labels:
    app: web
  namespace: ginflix
spec:
  selector:
    run: web
  type: LoadBalancer
  ports:  
  - name: web
    port: 30001
    targetPort: 8000
    protocol: TCP


